//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.1022
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nonoGrama.ServiceReferenceNanoGrama {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DiscreteTomography", Namespace="http://schemas.datacontract.org/2004/07/NonoGramaWS")]
    [System.SerializableAttribute()]
    public partial class DiscreteTomography : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[][] ColumnsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Error_CoordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Error_ValuesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[][] RowsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[][] Columns {
            get {
                return this.ColumnsField;
            }
            set {
                if ((object.ReferenceEquals(this.ColumnsField, value) != true)) {
                    this.ColumnsField = value;
                    this.RaisePropertyChanged("Columns");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error_Coord {
            get {
                return this.Error_CoordField;
            }
            set {
                if ((object.ReferenceEquals(this.Error_CoordField, value) != true)) {
                    this.Error_CoordField = value;
                    this.RaisePropertyChanged("Error_Coord");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error_Values {
            get {
                return this.Error_ValuesField;
            }
            set {
                if ((object.ReferenceEquals(this.Error_ValuesField, value) != true)) {
                    this.Error_ValuesField = value;
                    this.RaisePropertyChanged("Error_Values");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[][] Rows {
            get {
                return this.RowsField;
            }
            set {
                if ((object.ReferenceEquals(this.RowsField, value) != true)) {
                    this.RowsField = value;
                    this.RaisePropertyChanged("Rows");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceNanoGrama.INonoGramaService")]
    public interface INonoGramaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INonoGramaService/createNonoGrama", ReplyAction="http://tempuri.org/INonoGramaService/createNonoGramaResponse")]
        nonoGrama.ServiceReferenceNanoGrama.DiscreteTomography createNonoGrama(int n, int m, int[][] values);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INonoGramaServiceChannel : nonoGrama.ServiceReferenceNanoGrama.INonoGramaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NonoGramaServiceClient : System.ServiceModel.ClientBase<nonoGrama.ServiceReferenceNanoGrama.INonoGramaService>, nonoGrama.ServiceReferenceNanoGrama.INonoGramaService {
        
        public NonoGramaServiceClient() {
        }
        
        public NonoGramaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NonoGramaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NonoGramaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NonoGramaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public nonoGrama.ServiceReferenceNanoGrama.DiscreteTomography createNonoGrama(int n, int m, int[][] values) {
            return base.Channel.createNonoGrama(n, m, values);
        }
    }
}
